# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcc625ff5b21dd74533af219948f374ba8506793b745ee34bb0f6cfcb0ae6bcf461fcaf4fdb992068f1bfb377b3e62319ca0fcad9e2dac24257e12d9c422d009

test:
  secret_key_base: 0e8e501ef3d23c048d70309a50b66b4ef19a49af97b6d80d6d8c511340b67bfe992785fec5580633b4eca21d2c9c53824842650caa3cc15ed4dc81429cfce5cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
